### ISSUE TITLE
Can't install none of the MODELs.

### ISSUE THREAD

**Issue by art735** [jmyerston/greCy#7]
Hello!
I'm using Python 3.11.9 (x64) on Win10 and spaCy 3.5.3. Intallation of greCy itself raised no problems, but intallation of the models promises to finish (once started), but never actually does.

C:\Users\user>python -m grecy install grc_perseus_trf

Installing grc_perseus_trf.....

Please wait, this could take some minutes.....

C:\Users\user>

It states "Please wait, this could take some minutes....." and at this same time "releases" command execution and shows command prompt, inviting user to continue working with console...

**Comment by jmyerston** [comment]
Hi,

 I could not reproduce the issue.  It installs on linux and macosx. You can install the models directly from Huggingface. 

Please try the following as stated in the Huggingface hub:

pip install https://huggingface.co/Jacobo/grc_perseus_trf/resolve/main/grc_perseus_trf-any-py3-none-any.whl

# Using spacy.load().
import spacy
nlp = spacy.load("grc_perseus_trf")

# Importing as module.
import grc_perseus_trf
nlp = grc_perseus_trf.load()

**Comment by pletcher** [comment]
I've also intermittently run into an issue where the models fail to download, with no output or error to follow.

Running `pip install https://huggingface.co/Jacobo/grc_perseus_trf/resolve/main/grc_perseus_trf-any-py3-none-any.whl` gives

```
ERROR: Invalid requirement: 'grc-perseus-trf==any': Expected end or semicolon (after name and no valid version specifier)
    grc-perseus-trf==any
```

This is on an M1 Mac running Sonoma 14.5.

It's worth noting that I was able to install greCy about a week ago, but a week before that it failed in the same way.

I wish I could provide more help, but like I said, there aren't any errors to follow (except when attempting that `pip install`).

**Comment by pletcher** [comment]
I was able to get things working by rolling back to Python 3.11.9, after trying it on 3.12.4. Not sure if that's related to the issue encountered here at all, but `python -m grecy install grc_proiel_trf` finally worked when I recreated the venv from 3.11.9.

**Comment by art735** [comment]
> I've also intermittently run into an issue where the models fail to download, with no output or error to follow.
> 
> Running `pip install https://huggingface.co/Jacobo/grc_perseus_trf/resolve/main/grc_perseus_trf-any-py3-none-any.whl` gives
> 
> ```
> ERROR: Invalid requirement: 'grc-perseus-trf==any': Expected end or semicolon (after name and no valid version specifier)
>     grc-perseus-trf==any
> ```
> 
> This is on an M1 Mac running Sonoma 14.5.
> 
> It's worth noting that I was able to install greCy about a week ago, but a week before that it failed in the same way.
> 
> I wish I could provide more help, but like I said, there aren't any errors to follow (except when attempting that `pip install`).

I get the same error. I've tried to install and other .whl-packages from HuggingFace and always received this same error message.

UPDATE: The problem was with pip of version 24.1.2. After downgrading pip to its default for Python 3.11.9 version of 24.0, installation via .whl link has finally worked, but 'python -m grecy install grc_perseus_sm' still doesn't work.

What version of pip do you guys use? Maybe I should downgrade to an even earlier version of pip to get things work.

**Comment by jmyerston** [comment]
Thanks for reporting the problem. I have never encountered those issues myself. And I just installed grc_perseus_sm with the greCy installer. 

 My python version is 3.11.8 and pip 24.0.

**Comment by jmyerston** [comment]
You can also train the models yourself. The _sm and _lg will train without a GPU.
